export enum DirectaTradingCommands {
    INFOSTOCKS = "INFOSTOCKS",
    INFOAVAILABILITY = "INFOAVAILABILITY",
    DARWINSTATUS = "DARWINSTATUS",
    GETPOSITION = "GETPOSITION",
    INFOACCOUNT = "INFOACCOUNT",
    ORDERLIST = "ORDERLIST",
    ORDERLISTNOREV = "ORDERLISTNOREV",
    ORDERLISTPENDING = "ORDERLISTPENDING",
    // Add other commands as needed
}